spring.data.rest:
  returnBodyOnCreate: true
  returnBodyOnUpdate: true

logging.level: INFO
logging.level.org.hibernate.type.descriptor.sql: trace

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate.ddl-auto: create-drop
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mytest
    username: postgres
    password: 1
server.port: 8080

spring.jackson.serialization.fail_on_empty_beans: false
